move ああ？どうしてこんなに荒々しい態度をとるんだ？落ち着いて話を聞けばいいのに。.wav anger_regular_01.wav
move ああ？あの問題児がまた問題を起こしたって？何度注意しても改善しないんだから、もう本当に腹が立つ。.wav anger_regular_02.wav
move ああ？戦争を望むのか？どうしてこんなに愚かなことを言えるんだ。.wav anger_regular_03.wav
move ああ？罪悪感を感じるのは当たり前だろう！何をやっても全く反省していないのか？.wav anger_regular_04.wav
move ええ、自分勝手な考え方は許せないわ！周りの人たちの気持ちを考えなさい！.wav anger_regular_05.wav
move ええ、卑怯者め！人を裏切るなんて、どうしてそんなに卑しいことができるんだ！.wav anger_regular_06.wav
move ええ、気取った態度をとって何がしたいの？素直に話せばいいのに。.wav anger_regular_07.wav
move ええ、腹の立つことはわかるけど、怒りを爆発させる前に冷静に考えようよ。.wav anger_regular_08.wav
move おい、ぶっきらぼうに話すな！もうちょっと感情を込めて話してくれないと、こっちもイライラするぞ。.wav anger_regular_09.wav
move おい！あなたの過失で私たちは損害を被ったんだぞ！責任を取れ！.wav anger_regular_10.wav
move おい！失礼な態度は許されないぞ。謝罪して反省しなさい。.wav anger_regular_11.wav
move おい！あんた、暴挙を働いたって何がしたいんだ？自分がやられて嫌なことは、他人にもやるなんて許されることじゃないよ。.wav anger_regular_12.wav
move おのれ！何度も言い争いをしてばかりで何がしたいんだ？仲直りしろ！.wav anger_regular_13.wav
move おのれ！私たちは同僚なんだろう？なぜこんなに軽蔑的な態度を取るんだ？.wav anger_regular_14.wav
move おのれ！私怨で人を傷つけるなんて卑怯な行為だ。.wav anger_regular_15.wav
move おのれ！この地域は乱開発によって自然が破壊されているんだぞ！何も考えていないのか？.wav anger_regular_16.wav
move このー！あんたの過激な言動が問題なんだよ。周りの人の気持ちを考えて行動しろよ。.wav anger_regular_17.wav
move このー、どうしていつも消極的なんだ？もっと自分の意見をしっかりと主張しなさいよ。.wav anger_regular_18.wav
move このー！なぜあなたはいつも部屋を汚すの？もう一度やったら、怒りがおさまらないわよ。.wav anger_regular_19.wav
move このー！いくら争っても仕方がないと思わないか？和解しなさい。.wav anger_regular_20.wav
move こら！野蛮な言葉遣いはやめなさい。人を傷つけることに何の意味があるのか。.wav anger_regular_21.wav
move こら！あなたのよそ事に私がどう関わるんですか？私に迷惑をかけないでください。.wav anger_regular_22.wav
move こら！何でそんなに意地悪なんだよ？人を傷つけることでしか満足できないのか？.wav anger_regular_23.wav
move こら！こんな仕事、割に合わないって言ってたくせに、給料のことで文句を言うな！.wav anger_regular_24.wav
move なに？あなたが問題をこじらせたのに私が何も言わないと思うなよ。.wav anger_regular_25.wav
move なに！この鬼畜が！あなたのような人間がいるから世の中が腐るんだよ。.wav anger_regular_26.wav
move なに？濫行しているのに、まるで何も知らないかのように振る舞っているのか？.wav anger_regular_27.wav
move なに！こんなに汚い部屋で生活するつもりなの？早く片付けなさい！.wav anger_regular_28.wav
move ちぇっ、あなたの言い分は理不尽さしかないわ。私たちは平等に扱われるべきだ。.wav anger_regular_29.wav
move ちぇっ、傲慢な態度をとるくせに、何も知らないふりをしているなんてまじでありえない。.wav anger_regular_30.wav
move ちぇっ、あの人を恨む理由がないとでも思ってるの？あなたにとっては些細なことかもしれないけど、私にとっては大切なことだったんだよ。.wav anger_regular_31.wav
move ちぇっ、あなたの身勝手な行動はいつも私たちに迷惑をかけている。もう我慢できないわ。.wav anger_regular_32.wav
move はぁ？なぜこんなに急に解散することになったのか、説明してくれ。.wav anger_regular_33.wav
move はぁ？無駄遣いばかりして何が楽しいの？金を大事にしろよ。.wav anger_regular_34.wav
move はぁ？こんなに如何わしい商売しているとは知らなかったよ！信用していたのに。.wav anger_regular_35.wav
move はぁ？またお説教ですか？.wav anger_regular_36.wav
move ふん、いい加減にしろよ！いつもダメ出しばかりで何も褒め言葉がないんだ。.wav anger_regular_37.wav
move ふん、私が言いなりになると思っているのか？馬鹿げているわ。.wav anger_regular_38.wav
move ふん、今さら何を言っても遅いわ。あなたが咎められるべきことはもっと前から分かっていたはずよ。.wav anger_regular_39.wav
move ふん、私のプライバシーを侵害するなんて、どういうつもりだ？.wav anger_regular_40.wav
move もう！君がいつもそんなに無茶をするから、体を痛めるんだよ。反省しなさい！.wav anger_regular_41.wav
move もう、あなたの偏見には本当にうんざりするわ。人を見る目をもっと広げなさいよ。.wav anger_regular_42.wav
move もう、何度も夫婦喧嘩してどうするんだ？話し合いができないなら、もう別れた方がいいんじゃないか。.wav anger_regular_43.wav
move もう、あなたはいつも人を見下すばかりですね。本当に腹が立ちます。.wav anger_regular_44.wav
move ああ？押し付けがましいって、自分勝手に私の時間を割いてくるくせに何言ってるんだ？.wav anger_regular_45.wav
move ああ？最低な態度だよ。もう少しマナーを守れよ。.wav anger_regular_46.wav
move ええ、君の狭隘な考えは本当に腹立たしい。もっと広い視野を持って物事を考えろ。.wav anger_regular_47.wav
move ええ、お前は狡い奴だな。自分の利益のために他人を利用してばかりいる。.wav anger_regular_48.wav
move おい、不親切な態度はやめろよ！みんなが困っているときに、君だけが助けを拒むなんて許せない。.wav anger_regular_49.wav
move おい、いたしかたないって言われても納得できないんだよ。もっと努力しなさい！.wav anger_regular_50.wav
move おのれ！こんなインチキ商品を売っているとは何事だ！お金を返せ！.wav anger_regular_51.wav
move おのれ！あなたの不注意でここまで損害が出たんだぞ！どう責任をとるつもりだ？.wav anger_regular_52.wav
move このー、あなたは人生経験が足りないから、周りの人たちがどんなに苦労しているのか理解できないんでしょう？.wav anger_regular_53.wav
move このー！敗北したくなければ、もっと努力しなさいよ！.wav anger_regular_54.wav
move こら、何でいつも大切なことを後回しにするんだ？今すぐやればいいのに。.wav anger_regular_55.wav
move こら、荒削りな仕事をして、こんなもので満足できると思っているのか？もっと丁寧に仕上げなさい！.wav anger_regular_56.wav
move なに、また反乱を起こすつもりか？もう十分だ、静かにしていろ！.wav anger_regular_57.wav
move なに？白々しいことを言っているんじゃない！自分でやったことをちゃんと認めるべきだよ。.wav anger_regular_58.wav
move ちぇっ、私たちの提案が却下されたって本当ですか？もっと真剣に検討してくださいよ。.wav anger_regular_59.wav
move ちぇっ、あの悪女にはもううんざりだ。彼女の行動にはいつも怒りしか覚えない。.wav anger_regular_60.wav
move はぁ？政治不信を感じるのは当然でしょう！あの政治家は何もしないくせに、私たちを騙してるんだから！.wav anger_regular_61.wav
move はぁ？誰がこんなに大きな咆哮を上げたんだ？静かにしなさい！.wav anger_regular_62.wav
move ふん、被害者面するのはやめてください。自業自得だと思いますよ。.wav anger_regular_63.wav
move ふん、オヤジ臭いと言われたくなければ、自分で自分の身だしなみを気遣えよ。.wav anger_regular_64.wav
move もう！誰が暴行を働いたのか教えなさい。被害者のためにも、すぐに解決しなければなりません。.wav anger_regular_65.wav
move 陰謀を企んでいたなんて信じられない！もう、二度と会わないでくれ！.wav anger_regular_66.wav
move いや、あんな醜い人間を見るのは本当に嫌だ。.wav disgust_regular_01.wav
move いや、あの人は恥ずかしくなるほど下品な言葉遣いをするんだよ。.wav disgust_regular_02.wav
move いや、あの人が嫌いすぎて顔を見るだけで吐き気がするんだ。.wav disgust_regular_03.wav
move いや、そのような不道徳な行為をしている人たちは、社会的に唾棄されるべきだと思います。.wav disgust_regular_04.wav
move いや、あの人の臭さはただの不潔さではなく、もう何日も風呂に入っていないような臭いで、本当に我慢できない。.wav disgust_regular_05.wav
move いや、あの家は本当にみすぼらしい。中に入る前から不快な気分になる。.wav disgust_regular_06.wav
move いや、あの人の話は聞き苦しいほどつまらない。もう２度と話しかけないで欲しい。.wav disgust_regular_07.wav
move あの人はいつも自分のことばかりで周りを全く考えていない、独善的な人間なんだよね。うあ、嫌だ。.wav disgust_regular_08.wav
move うあ、君の言葉は本当に私を傷つけましたよ。もう二度とそんなこと言わないでください。.wav disgust_regular_09.wav
move うあ、あの専横な上司には本当に辟易としてしまいます。仕事ができるとは言え、人間性が欠如していると思います。.wav disgust_regular_10.wav
move うあ、この排水溝のにおいはまさに人間の排泄物のようです。.wav disgust_regular_11.wav
move うあ、あの卑しい男がまた私に近づいてきた。本当に嫌だ。.wav disgust_regular_12.wav
move うあ、あの人は本当に音痴で、歌を聞くと耳が痛くなるよ。.wav disgust_regular_13.wav
move うあ！下痢は本当に嫌だ。トイレに行くたびにお腹が痛くなって、もう我慢なんてできない。.wav disgust_regular_14.wav
move この場所は臭くて、音もうるさくて、人も多すぎる、うぇ！ここにいるのは本当に嫌だ。.wav disgust_regular_15.wav
move うぇ、誰がこんなに綺麗な場所に排泄物を捨てるんだろう？ほんとうに気持ち悪い。.wav disgust_regular_16.wav
move うぇ、水疱瘡って本当に不快な病気ですよね。赤くてかゆくて、見ているだけで気持ちが悪くなります。.wav disgust_regular_17.wav
move うぇ！誰かが屁をこいた臭いがする。すごく不快だ。.wav disgust_regular_18.wav
move うぇ、また水漏れが起きている。この湿気とカビ臭い匂いは本当に嫌だ。.wav disgust_regular_19.wav
move うぇ、このシミは何？臭いし、見ているだけで気分が悪くなる。.wav disgust_regular_20.wav
move うぇ、泥水を飲むなんて考えられないわ。あんな汚い水で病気になるだけよ。.wav disgust_regular_21.wav
move うわ、あの人の考え方は完全に非合理的だ。話を聞いているだけで頭が痛くなる。.wav disgust_regular_22.wav
move うわ、またステレオタイプな考え方を持っている人がいるんだ。本当に嫌になるよ。.wav disgust_regular_23.wav
move うわ、あんな醜悪な顔をしていたら誰も近寄ってきませんよ。.wav disgust_regular_24.wav
move うわ、あの毒舌女性は本当に他人の気持ちを考えずに人を傷つける言葉ばかり吐きますね。.wav disgust_regular_25.wav
move うわ、あんなにたくさんの人がいる人ごみに入るなんて嫌です。息苦しくて動けないし、汗でベタベタして不快感しかありません。.wav disgust_regular_26.wav
move うわ、この靴下は臭くてなじまない！もう二度と履きたくない！.wav disgust_regular_27.wav
move うわ、あの人の妄想に巻き込まれたくない。一緒にいると気持ち悪い。.wav disgust_regular_28.wav
move ええ、そんな悪癖を持っている人は近づきたくないですね。.wav disgust_regular_29.wav
move ええ、本当にしつこいですね。もうやめてください。.wav disgust_regular_30.wav
move ええ、あの横暴な態度を持つ人と付き合うのは本当にむり。どうにかしてくれ。.wav disgust_regular_31.wav
move ええ、どう見てもこのチーズは腐敗しているだろう？食べるのは絶対に嫌だ。.wav disgust_regular_32.wav
move ええ、掃除とかめんどう臭くて、.wav disgust_regular_33.wav
move ええ、あの寝汗の臭いは本当に嫌でたまらないです。.wav disgust_regular_34.wav
move ええ、伝染病にかかったら本当に大変ですよ。私はそのような危険を冒すのは嫌です。.wav disgust_regular_35.wav
move おえ、腸炎になったらトイレにこもりっきりで、吐き気や下痢に苦しみますよ。.wav disgust_regular_36.wav
move おえ、こんなに不健康なものを食べるなんて、本当に吐き気がする。.wav disgust_regular_37.wav
move おえ、二日酔いって本当に最悪ですね。頭が痛くて、吐き気がして、体がだるくて、食欲もない。.wav disgust_regular_38.wav
move おえ！部屋に入った瞬間、異臭がして私は気持ち悪くなってしまった。.wav disgust_regular_39.wav
move おえ！あの不浄な男がまたここにいる！彼の体臭は臭いというよりも、生ごみが腐ったような匂いがする。.wav disgust_regular_40.wav
move おえ！あの膿腫がまた大きくなってしまった。匂いがひどく、見るだけで胃が痛くなる。.wav disgust_regular_41.wav
move おえ！あの鼠がまた出た！その汚らしい尻尾を見るだけで、私の背筋が凍りつく。.wav disgust_regular_42.wav
move あの汚いトイレには病原菌がいっぱいだ、げっ。近づくのも嫌だ。.wav disgust_regular_43.wav
move げっ、こんなに汚い泥沼の中には入りたくないです。.wav disgust_regular_44.wav
move げっ、あの汚い食べ物を見たら反吐が出そうになります。.wav disgust_regular_45.wav
move げっ、伝染病にかかった人が近くにいたら、私はすぐにその場から逃げたい。.wav disgust_regular_46.wav
move げっ、あの人の指からヤニが滴り落ちている。気持ち悪い！.wav disgust_regular_47.wav
move げっ、その酒乱野郎がまた来たの？今度こそ警察に通報するわ！.wav disgust_regular_48.wav
move げっ、なんであそこに虫たちが群がっているかと思ったら、腐った羊の死体があります。.wav disgust_regular_49.wav
move いや、あんな些細なことで過剰反応するなんて、どうしようもなくて不快だ。.wav disgust_regular_50.wav
move いや、あの身勝手な態度には本当に腹が立ちます。自分勝手に行動する人は本当に嫌いです。.wav disgust_regular_51.wav
move いや、あなたの投げやりな態度は本当に不愉快ですよ。もっと責任を持って仕事をしてください。.wav disgust_regular_52.wav
move うあ、この生臭い匂いは何？この食べ物は腐っているんじゃないかと思うほど不味い！.wav disgust_regular_53.wav
move うあ、私はこのような不潔な場所で仕事をするつもりはない。即座に掃除をしなければ、私はこの取引を中止する。.wav disgust_regular_54.wav
move うぇ、こんなに酷い話を聞いたのは初めてだわ。もう聞きたくない！.wav disgust_regular_55.wav
move うぇ、こんなドロドロしたもの触るの無理！誰かやって！.wav disgust_regular_56.wav
move うわ、この音楽、騒がしすぎて集中できないよ。.wav disgust_regular_57.wav
move うわ、何でこんなに人が多いんだよ！もう一歩も動けないじゃないか！.wav disgust_regular_58.wav
move ええ、本物と思ったら偽者だったなんて本当に信じられない。気持ち悪い！.wav disgust_regular_59.wav
move ええ、この水の中にはあんなに濁りがあって、見るに堪えませんね。.wav disgust_regular_60.wav
move おえ、この醜態を見て！もう目を背けたくなるわ！.wav disgust_regular_61.wav
move おえ、あの汗臭いTシャツを着てる人、電車の中でかなり臭くなってきてるよ。.wav disgust_regular_62.wav
move げっ、この虫が体に触れたら、気が狂いそう！.wav disgust_regular_63.wav
move げっ、このドアノブがベタベタしているのは、何なのよ！.wav disgust_regular_64.wav
move うわ、不景気の影響で失業してしまうかもしれない。どうしよう、心配で眠れない。.wav fear_regular_01.wav
move うわ、世界的な経済危機が起きたら、私たちの生活はどうなるんだろう。.wav fear_regular_02.wav
move うわ、地震だ！早く逃げろ！.wav fear_regular_03.wav
move うわ、あの暴風雨はきっと災いをもたらすに違いない。.wav fear_regular_04.wav
move 山奥で突然熊に遭遇して、慄然として声も出なかった。うわ、どうしよう。.wav fear_regular_05.wav
move うわ、核戦争が起こったら、人類は滅びるかもしれない。.wav fear_regular_06.wav
move うわ、昨日のニュースで暴行事件が起こっていたなんて知らなかった。今夜は怖くて眠れない。.wav fear_regular_07.wav
move きゃあ、ここは夜遊びする場所じゃない。周りが物騒な感じがして、怖い。.wav fear_regular_08.wav
move きゃあ、あの人たちはパニックに陥り始めている。何かが起こる前触れなのかもしれない…。.wav fear_regular_09.wav
move きゃあ！ばい菌に感染してしまったら大変なことになる！早く医者に診てもらわなきゃ。.wav fear_regular_10.wav
move あの山が噴火したら、周りの人々はみんな犠牲になってしまう、きゃあ、早く避難しなければ！.wav fear_regular_11.wav
move 夜の森で、人を食ったと噂される熊に出くわした！きゃあ、助けてください！.wav fear_regular_12.wav
move きゃあ、あの建物の廃墟が不気味すぎて、中に誰かいるような気がして怖くて入れない。.wav fear_regular_13.wav
move きゃあ、あの森は暗くて怖いですね。一人で歩くのは危険かもしれません。.wav fear_regular_14.wav
move ぎゃあ、内乱が勃発したらどうしよう。生活が壊れ尽くしたり、身の安全が脅かされたりするかもしれない。.wav fear_regular_15.wav
move ぎゃあ、昨日夜中に脅迫電話がかかってきた。もう一人で家にいるのは怖いなあ。.wav fear_regular_16.wav
move ぎゃあ、新しいウイルスが変異したと聞いて、これ以上どうなるか分からない世界に生きていると思うと怖くてたまらない。.wav fear_regular_17.wav
move ぎゃあ！放射性物質が漏出していると聞いて、周りの人々は一斉にパニックに陥った。.wav fear_regular_18.wav
move ぎゃあ、この険しい山道を歩くのは本当に怖い！.wav fear_regular_19.wav
move ぎゃあ、この山道は本当に隘路だ。一歩間違えれば崖に転落するかもしれない。.wav fear_regular_20.wav
move ぎゃあ、あの恐るべき巨大な竜巻が私たちの方に向かって来ています！早く避難しましょう！.wav fear_regular_21.wav
move ひっ、昨夜見た悪夢があまりにも恐ろしかったので、今でも震えが止まりません。.wav fear_regular_22.wav
move ひっ、傷口から細菌が入って敗血症になったら、もう手遅れになってしまうかもしれない。早く病院に行かなければ。.wav fear_regular_23.wav
move ひっ、あの小学生が誘拐事件に巻き込まれてしまったと聞いて、子供を持つ親として恐怖でいっぱいになってしまった。.wav fear_regular_24.wav
move ひっ、この雨が続けば、もしかしたら大洪水になるかもしれない。すぐに避難しなければ。.wav fear_regular_25.wav
move 怖い話を聞いて、私の腕には鳥肌が立ち上がっている、ひっ、何かが見えるような気がして怖い。.wav fear_regular_26.wav
move ひっ、この厳寒の中、山奥で迷子になったらどうしよう。生きて帰れるかな？.wav fear_regular_27.wav
move 森の奥にいる獣の鳴き声が怖い、ひっ、もう帰りたい。.wav fear_regular_28.wav
move ひい、今日のニュースで聞いた事件は、私が住むこの町で起こったんだ。怖くて外出するのが怖くなってきた。.wav fear_regular_29.wav
move ひい、この事件は単独犯の仕業だと思うと、犯人がまだ逃げているかもしれないことが怖い。.wav fear_regular_30.wav
move ひい、街の抗争が激化して、いつ自分が巻き込まれるか分からない。.wav fear_regular_31.wav
move 夜道を歩いていたら、ひい、暴走族のバイク団が突然やって来た。怖くて足がすくんだ。.wav fear_regular_32.wav
move ひい、あの暴行事件は本当に怖かった。もう二度とあんな体験はしたくない。.wav fear_regular_33.wav
move あの建物は地震の後から不安定のままになっていた、ひい、今いるのはとても危険だ。.wav fear_regular_34.wav
move ひい！あそこには難破した船がある。今夜は海が荒れているから、近づかない方がいいよ。.wav fear_regular_35.wav
move ひえ、このまま長雨が続くと、農作物が壊滅的な被害を受け、飢饉が起こるかもしれません。.wav fear_regular_36.wav
move 地震の被害に遭った人たちの苦しみを想像すると、ひえ、自分たちも同じような被害に遭うかもしれないと不安になる。.wav fear_regular_37.wav
move ひえ、テロリズムが蔓延する世界で生きることが怖くて何もできない。.wav fear_regular_38.wav
move ひえ、弱者が社会に踏み潰されるのを見ると、自分も同じようになってしまうのではないかと不安になる。.wav fear_regular_39.wav
move ひえ、怖くて腰抜けになりそうだ！あそこにいるのはサイコパスの殺人犯だ！.wav fear_regular_40.wav
move 山中で追われているとき、後ろから迫ってくる殺気を感じて、ひえー、もうダメだと思った。.wav fear_regular_41.wav
move あの事件以来、私は疑心暗鬼に陥っている、ひえ、誰が友達で誰が敵か分からない。.wav fear_regular_42.wav
move わあ、あの映画のシーンで見たような残忍な殺し方を想像するだけで、怖くてたまらない。.wav fear_regular_43.wav
move わあ、突然の戒厳令で街中が騒然となった。このままでは何が起こるかわからない。.wav fear_regular_44.wav
move 敵軍から一斉射撃が始まったとき、わあ、私は本当に怖くて身動きができなかった。.wav fear_regular_45.wav
move わあ、昨日夜中に家の前でストーカーがいたんです！怖くて一晩中眠れませんでした。.wav fear_regular_46.wav
move あの男性の威圧的な態度に、わあ、私は怖くて声も出せなかった。.wav fear_regular_47.wav
move わあ、国の通貨危機で物価が暴騰して、買い物ができなくなるかもしれない。.wav fear_regular_48.wav
move わあ、国の政府がクーデターに遭ったのは聞いていたけど、今自分の目で見ると怖すぎて心臓が止まりそうだ。.wav fear_regular_49.wav
move いや、胸が張り裂けそうだ…この暗闇でひとりになったら、絶対に殺される…！.wav fear_regular_50.wav
move いや、あの人の目が怖すぎて…何か言われる前に逃げ出したい…！.wav fear_regular_51.wav
move いや、この辺りには何か悪いものが潜んでいるに違いない…！逃げなきゃ…！.wav fear_regular_52.wav
move いや、あの音は何だ…？ああっ！誰か来た…！逃げろ…！.wav fear_regular_53.wav
move いや、あの人の笑い声が耳に残る…こんなに不気味な笑い声を聞いたことがない…！.wav fear_regular_54.wav
move いや、ここは絶対におかしい…！何か異常な感じがする…！.wav fear_regular_55.wav
move いや、あの人の目つきが…嫌な予感がする…逃げなきゃ…！.wav fear_regular_56.wav
move いや、あの影が…何だ、あの影は…？！.wav fear_regular_57.wav
move いや、こんなに寒くなるなんて…何かが起こる前触れなのかもしれない…！.wav fear_regular_58.wav
move いや、何かが背後にいる…もう動けない…！.wav fear_regular_59.wav
move うわ、あの巨大な怪物が迫ってくる、恐怖で足がすくんでしまう。.wav fear_regular_60.wav
move うわ、あの大震災以来、凶報を聞くたびに震えが止まらなくなる。.wav fear_regular_61.wav
move あの巨大な嵐が近づいている、きゃあ、このままでは町に災禍が降りかかる！.wav fear_regular_62.wav
move あの森の中には、怪異な存在が潜んでいると噂されています。きゃあ、行くのはやめよう！.wav fear_regular_63.wav
move ぎゃあ！何も知らないで電気回路に触れたら、感電してしまうよ！.wav fear_regular_64.wav
move ぎゃあ、この森には危険な毒蛇が生息していると聞いた。もう二度と来ることはない！.wav fear_regular_65.wav
move ひっ、医師から肝臓がんの診断を受けたと聞いて、私は恐怖で震えた。.wav fear_regular_66.wav
move あの人たちはテロリストだと言われているんだ、ひっ、こんなところで遭遇したらどうしよう。.wav fear_regular_67.wav
move ひっ、この国はまた動乱に陥ってしまったのか。ますます危険になりそうだ。.wav fear_regular_68.wav
move ひい！あの犯人は逃亡中だと聞いた。もし彼がこの近くにいたらどうしよう。.wav fear_regular_69.wav
move ひい！あの蛇はとても危なそうだ、毒液にやられたら死んでしまうかもしれない。.wav fear_regular_70.wav
move ひい、あの建物からは死人が出たという噂を聞いたよ。.wav fear_regular_71.wav
move ひい！目の前で暴力行為が行われている！早く警察に通報しなければ。.wav fear_regular_72.wav
move ひえ、高速道路でアクシデントが起こったようです。もしかしたら私たちにも影響があるかもしれません。.wav fear_regular_73.wav
move ひえ、彼の吐血した姿を見たとき、私は本当に怖かった。.wav fear_regular_74.wav
move わあ、あの拷問の方法は本当に残忍です。誰かが助けに来る前に私たちは狂ってしまうかもしれません。.wav fear_regular_75.wav
move わあ、今日の嵐はとても恐ろしいですね。家に帰って避難しなくては！.wav fear_regular_76.wav
move わあ、あの狂人は私たちを襲うかもしれないから、近づかない方がいいです。.wav fear_regular_77.wav
move 今日の山登りは最高だった！山頂で見た景色は言葉に表せないほど美しかった！あはは、絶頂の喜びが胸に溢れるよ！.wav happy_regular_01.wav
move あはは、昨日の授賞式で私の友達が最優秀女優賞を受賞したんだ！本当に素晴らしい演技だったよ。.wav happy_regular_02.wav
move 昨日、宝くじを買ったら、100万円が当たったよ！あはは、ラッキー！.wav happy_regular_03.wav
move イエーイ！私たちの会社は新しい製品のおかげで知名度が急上昇しているんだ！顧客からの反応もすごく良くて、本当に嬉しいよ！.wav happy_regular_04.wav
move イエーイ！今日は手頃な価格で美味しい食事を楽しめたんだ！.wav happy_regular_05.wav
move 昨日、サーフィンを初めて体験してきたよ！イエーイ！波に乗る感覚は最高だった！.wav happy_regular_06.wav
move うおー！私たちのチームが決勝ゴールを決めた瞬間は、本当に感動的だったよ。みんなで喜びの声を上げたね。.wav happy_regular_07.wav
move うおー、久しぶりに会った友人と一緒に過ごす時間は最高だった！会話も盛り上がって、本当に楽しかった！.wav happy_regular_08.wav
move うおー、今日は海で泳ぐのが本当に気持ちがいい！さっきまで暑かったのに、海に入ったら涼しい風が吹いて最高だったよ。.wav happy_regular_09.wav
move 昨日私は自分の目標を達成したんだ！うふふ、こんなに嬉しいことはないよ！.wav happy_regular_10.wav
move うふふ、私たちのグループは真の友愛の精神で結ばれています。本当に幸せです。.wav happy_regular_11.wav
move うふふ、お正月にもらったお年玉で新しいスマホを買っちゃった！もう写真撮るのが楽しくて楽しくて！.wav happy_regular_12.wav
move ええ、彼女は本当に素晴らしい美声を持っている。聴くだけで幸せな気分になる。.wav happy_regular_13.wav
move ええ、今日の夕飯は最高だった！手作りのピザとデザートがあって、お腹も心も満たされた感じがして最高に満足感があるよ。.wav happy_regular_14.wav
move ええ、このリゾートホテルのプールは本当に心地よい。水の温度もちょうどいいし、景色も最高だよ。.wav happy_regular_15.wav
move 今、私は大学の合格通知をもらったんだ！えへへ、歓喜のあまり飛び跳ねたくなるぐらいうれしい！.wav happy_regular_16.wav
move 今日は友達にたくさん手伝ってもらって、とっても感謝してるんだ。えへへ、本当にありがたい！.wav happy_regular_17.wav
move 昨日、オークションで逸物の刀を手に入れたんだ！えへへ、これで私の刀コレクションも充実したよ！.wav happy_regular_18.wav
move おお、昨日、私の大ファンが私の曲をカバーしてくれたところを見たんだ！それを見て、とても幸せになったよ。.wav happy_regular_19.wav
move おお、私の祖母は手術を受けた後、ついに完全に治癒したんだ！元気いっぱいになって本当に良かった！.wav happy_regular_20.wav
move おお！私はついに英語の資格試験に合格して、認定されたよ！これで英語がもっと話せるようになるぞ。.wav happy_regular_21.wav
move 今回の選挙で、私のおじいさんが得票数1位を獲得したんだ！はは、家族全員でお祝いするよ！.wav happy_regular_22.wav
move はは、今日の運動会は楽しかったね！特にリレーの時はみんなが協力して走ってくれたから、最高の思い出になったよ。.wav happy_regular_23.wav
move はは、本当にラッキーだった！今日の抽選で、1等賞を当てたんだ！それも、夢にまで見たヨーロッパ旅行が当たったんだ！.wav happy_regular_24.wav
move 彼女が私にほほ笑みを浮かべてくれたとき、とっても嬉しかったんだ。ふふ、幸せな気持ちでいっぱいだ。.wav happy_regular_25.wav
move 最近、自分の人生に充実感を感じているんだ。友達、家族、そして仕事もうまくいっている。ふふ、本当に幸せだ.wav happy_regular_26.wav
move ふふ、今日のデートはロマンティックだった！夜景を見ながら手を繋いで、とても幸せな気持ちになったよ。.wav happy_regular_27.wav
move 昨日のイベント、大盛況だったよ！たくさんの人が来てくれて、へへ、すごく嬉しかった！.wav happy_regular_28.wav
move 今日はスーパーで買い物したら、予想外にキャッシュバックがもらえたんだ！へへ、ラッキー！.wav happy_regular_29.wav
move 彼女の誕生日プレゼント、ぴったりのものを見つけたんだ！へへ、喜んでもらえるといいな。.wav happy_regular_30.wav
move やった！ついに私たちの会社が世界進出することになったんだ！私たちは世界中の人々にサービスを提供できるんだ！.wav happy_regular_31.wav
move 私たちの国と彼らの国との友好協定が結ばれた！これでより良い関係を築いていけるね。やった！.wav happy_regular_32.wav
move やった！私たちが買った株式は高値で売れたんだ！大金を手に入れたよ！.wav happy_regular_33.wav
move よし、彼女は一生懸命勉強して、ついに大学に合格したんだ！彼女の頑張りが報われて、とても嬉しいよ！.wav happy_regular_34.wav
move 今日は天気が良くて、友達と楽しく過ごせた！本当にいい気持ちだよね！よし、また来週も会おう！.wav happy_regular_35.wav
move よし、最後のピッチャー交代が功を奏して、我がチームは逆転勝利を手にした！感動的な瞬間だったな。.wav happy_regular_36.wav
move よっしゃ！私の友達が有名なアーティストと一緒に写真を撮ってくれたんだ！これで私も有名人と写真が撮れた！.wav happy_regular_37.wav
move 今日の創作のレッスンは本当にすごかった！私たちの想像力は完全に解放された！よっしゃ、これから私たちは素晴らしい作品を作り出せるぞ.wav happy_regular_38.wav
move よっしゃ！おじいちゃんの遺産で家を買えるようになったよ！これで家族みんなで快適に暮らせる！.wav happy_regular_39.wav
move わぁ、お客様からとても感謝の言葉をもらったよ！私たちのサービスがお客様にとって役に立っていると知って、とっても嬉しい！.wav happy_regular_40.wav
move わぁ、ついに私たちは日本一になった！全国大会での勝利は、長年続いた練習の成果が実ったことを証明しているよ。.wav happy_regular_41.wav
move わぁ、今日はプロジェクトを完成させたんだ！本当に大変だったけど、クライアントからのフィードバックを聞いて、この仕事にやりがいを感じているよ！.wav happy_regular_42.wav
move わーい、私の代表作が出版されたよ！これで私の作品がたくさんの人に読まれるんだ！.wav happy_regular_43.wav
move わーい、あの新しい同僚は本当にフレンドリーで、一緒に仕事するのが楽しいんだ！.wav happy_regular_44.wav
move わーい、今日のディナーはとっても美味しかった！お腹いっぱいで満足だよ！.wav happy_regular_45.wav
move ヤッホー！今日のプレゼンテーションはとても素晴らしかった！ナイスな仕事だったね。.wav happy_regular_46.wav
move ヤッホー、今日の夕陽は麗しい！こんなに美しい光景を見ることができて、本当に幸せだね。.wav happy_regular_47.wav
move ヤッホー！今日の天気、ちょうどいい感じだね！風も涼しくて最高！一緒に散歩しよう。.wav happy_regular_48.wav
move あはは、ついに頭痛が治った！普通に生活できるようになって、本当に嬉しい。.wav happy_regular_49.wav
move 今度の週末は友達と旅行するんだ！あはは、楽しみすぎて今からワクワクしてる！.wav happy_regular_50.wav
move あはは、この香りは本当に素晴らしい！フランスのラベンダー畑で育ったような、甘く優雅な香りだね。.wav happy_regular_51.wav
move 今回の試合で、彼はトップクラスのパフォーマンスを見せてくれたよ！あはは、すごいね！.wav happy_regular_52.wav
move イエーイ！長い時間かかったけど、私たちは目的達成したよ！これで次のステップに進むことができる！.wav happy_regular_53.wav
move イエーイ！私たちのチームは昨日の試合で圧勝したよ！まさかこんなに差がつくとは思わなかった！.wav happy_regular_54.wav
move うおー、今日のハイキングで見た山頂からの絶景は本当に素晴らしかった！空気も澄んでいて、心が洗われた感じがする。.wav happy_regular_55.wav
move うおー、今日は本当に幸せな日だね。家族と一緒に過ごして、美味しい料理を食べて、笑い合って、こんなに幸せな瞬間はないよ。.wav happy_regular_56.wav
move うおー、ついに私たちのチームがこの大会で受賞したよ！みんなの努力が報われたね。.wav happy_regular_57.wav
move この町に引っ越してきてから、新しい友達にも出会えて、職場の人間関係も良くなって、うふふ、本当に良いことばかりだ。.wav happy_regular_58.wav
move うふふ、私たちのビジネスが成長して、収益が倍増したんだ！これで新しいプロジェクトを始めることができるよ！.wav happy_regular_59.wav
move あのホテルの部屋、広くて景色も最高で、ベッドも快適だったよ！うふふ、最高の宿泊体験だった！.wav happy_regular_60.wav
move ええ、私は文化人類学に興味があるんだ。異文化を学ぶことがすごく面白いと思うから。.wav happy_regular_61.wav
move ええ、私が今日会った新しい同僚は、とても誠実な人でした。こんなに素晴らしい人と出会えたことに感謝します。.wav happy_regular_62.wav
move ええ、ついに私は昇進したよ！新しいポジションで自分の力を試せるってとっても嬉しい。.wav happy_regular_63.wav
move えへへ、私の新しい家具は高級な無垢材でできているんだ。こんな美しいものを手に入れられるなんて、とっても幸せ！.wav happy_regular_64.wav
move あの人の魅力的な笑顔に魅了されちゃった！えへへ、もう幸せすぎる.wav happy_regular_65.wav
move 今日は久しぶりに友達とのデートだ！楽しみでうきうきしているよ。えへへ。.wav happy_regular_66.wav
move おお、私たちのチームは今月の売り上げを前月比で２０％向上させたんだ！.wav happy_regular_67.wav
move おお、部屋の片付けが終わった！これで気持ちがすっきりした。.wav happy_regular_68.wav
move おお、新しいプロジェクトに参加することで私のモチベーションが上がってきたよ！.wav happy_regular_69.wav
move おお、彼女は本当にカリスマ的なリーダーシップを持っている。彼女がいるから、私たちはいつも自信を持って前進できるんだ。.wav happy_regular_70.wav
move 最近、ジョギングを始めてから毎日の生活に活力が湧いている！はは、もっと早くから始めればよかった！.wav happy_regular_71.wav
move 今夜の晩御飯は豪勢に牛ステーキを食べたんだ！はは、贅沢すぎる！.wav happy_regular_72.wav
move はは、私は今週末に友達と一緒に行くロッククライミングに対して興味津々だよ！楽しみだ！.wav happy_regular_73.wav
move ふふ、私の料理のレパートリーが増えたよ！新しいレシピを試してみたら、美味しくできたんだ。.wav happy_regular_74.wav
move 先日、私の子供が初めて自分で靴を履いたんだ。ふふ、とっても微笑ましい光景だったよ。.wav happy_regular_75.wav
move へへ、ついに自立する日が来たんだ！これから自分でお金を稼いで生活できるようになるんだ！.wav happy_regular_76.wav
move 新しい職場で初めての日は少し緊張したけど、周りの人たちがとても優しくて、へへ、すぐになじめたんだ！.wav happy_regular_77.wav
move 私たちのチームが先制ゴールを決めたよ！やった！私たちは勝つことができるはずだ！.wav happy_regular_78.wav
move 今日のマラソン大会で、私は自分の全力を出し切って、1位になったんだ！やった！.wav happy_regular_79.wav
move よし、彼女のリーダーシップがあってこのプロジェクトが成功したんだ！私たちのチームは素晴らしい！.wav happy_regular_80.wav
move よし、今日は一日中勉強して、とても充実感がある！自分を褒めてあげたい。.wav happy_regular_81.wav
move よっしゃ！今日から有休をとって、ハワイ旅行に行くぞ！泳いで、日光浴して、最高のリフレッシュをするんだ！.wav happy_regular_82.wav
move よっしゃ！今日はボーナスが出たよ！これで旅行に行くお金が貯まるぞ！.wav happy_regular_83.wav
move わぁ、今日のコンサートは最高だった！あの歌手は本当に才能があるね。.wav happy_regular_84.wav
move わぁ、この薬が奏効して痛みが和らいだ！もう少しで快復できそうだ！.wav happy_regular_85.wav
move わーい、この毛布は本当にぬくもりがあって、寒い夜でも心地よく眠れる！.wav happy_regular_86.wav
move わーい！私は今日のテストで学力がアップしていることがわかったよ。.wav happy_regular_87.wav
move ヤッホー！今朝読んだ記事が面白すぎて、仕事中もずっと笑ってたよ！.wav happy_regular_88.wav
move ヤッホー！昨日から筋力トレーニングを始めたんだけど、もう今日は筋肉痛！これからも頑張って鍛えるぞ！.wav happy_regular_89.wav
move あーあ、昨日の事故で大切な車が全損になっちゃった。もうどうしようもないよ。.wav sad_regular_01.wav
move あーあ、今日の試合は逆転負けで、本当に悔しい。頑張ったのに、最後まで勝てなかったのはつらい。.wav sad_regular_02.wav
move あーあ、仕事が思うように進まなくて、フラストレーションが溜まっている。もう少し頑張ればいいとわかっているけど、今は本当に悲しい気持ちでいっぱいだ。.wav sad_regular_03.wav
move あーあ、おばあちゃんが肺がんになったと聞いて、とても悲しくて胸が苦しくなりました。.wav sad_regular_04.wav
move あーあ、また新型コロナの感染者が増えて、隔離されなくちゃいけなくなった。友達と会えなくて、本当に悲しい。.wav sad_regular_05.wav
move あーあ、毎日残業が続いて疲れるばかりで、家族と過ごす時間も減ってしまって、悲しい気持ちでいっぱいです。.wav sad_regular_06.wav
move あーあ、大切なお茶をこぼしてしまった。母からもらったものだったのに。.wav sad_regular_07.wav
move あぁ、山道を歩いていたら落石に遭遇してしまって、大怪我をしてしまった。本当に運が悪かったです。.wav sad_regular_08.wav
move あぁ、私が大切に育てていた花が枯死してしまった。もう見ることもできないと思うと悲しくて仕方がない。.wav sad_regular_09.wav
move あぁ、昨日の夜、自動車事故に遭ってしまって、相手の方が亡くなってしまった。自分が生きていることが辛くて仕方がない。.wav sad_regular_10.wav
move あぁ、彼の裏切りが私の人生に破滅的な影響を与えて、もう何もかもが意味をなさなくなった。.wav sad_regular_11.wav
move あぁ、あの大切な思い出の品を忘失してしまった。懐かしい思い出が一瞬で消えてしまったような気がして、寂しくなってしまった。.wav sad_regular_12.wav
move あぁ、この仕事をしていても何か虚しい気がして、自分がやりたかったこととは違う人生を歩んでいるようで悲しい。.wav sad_regular_13.wav
move あぁ、祖母が危篤状態で、もうすぐこの世を去ってしまうかもしれない。悲しくて心が痛む。.wav sad_regular_14.wav
move うう、自己嫌悪に陥ってしまって、自分自身が嫌いになってしまった。どうしたらいいか分からない。.wav sad_regular_15.wav
move うう、スマホの容量不足で写真を撮れなくなってしまった。思い出を残すことができなくて残念でした。.wav sad_regular_16.wav
move うう、今日の試合は本当に惨敗だった。全然勝てる気がしなかったけど、やっぱり負けるとこんなに悔しいんだな。.wav sad_regular_17.wav
move うう、上司には逆らえなくて、自分の意見さえいえない。.wav sad_regular_18.wav
move うう、彼女にフラれたのは本当に悔しい。こんなに愛しているのに、どうして私とは一緒にいたくないのか。.wav sad_regular_19.wav
move うう、別れが近づいているのに、どうして彼は全然悲しんでいないんだろう。私だけが一人きりで切ない思いをしている。.wav sad_regular_20.wav
move うう、あの時助けられなくて、自分の無力さを痛感した。.wav sad_regular_21.wav
move うわあ、あの人が私に言ったことは全部ウソだったと知って、本当に悲しくて涙が出てきた.wav sad_regular_22.wav
move うわあ、父が末期ガンだと診断された。手遅れだと言われて、何もできない自分が情けなくて悲しい。.wav sad_regular_23.wav
move うわあ、この仕事での苦労が報われないと思うと、本当に悲しくて辛い。.wav sad_regular_24.wav
move うわあ、昨日のマラソン大会で体力不足でゴールできなかった。みんなに失望された気がする。.wav sad_regular_25.wav
move うわあ、留学先で初めてのクリスマスを一人で過ごすことになって、とっても寂しくて泣きそうだ。.wav sad_regular_26.wav
move うわあ、大切な友情を損なってしまった、どうして私はこんなことをしてしまったんだろう。.wav sad_regular_27.wav
move うわあ、昨日のニュースであの殺人事件の被害者が知り合いだったと知って、とても悲しくなってしまった。.wav sad_regular_28.wav
move えーん、大好きだった船が沈没してしまって、もう二度と乗れないと思うと胸が痛い。.wav sad_regular_29.wav
move えーん、私の人生はもう破滅したみたい。大切な人を失って、仕事もうまくいかなくて、何もかもがうまくいかない。.wav sad_regular_30.wav
move えーん、私は歌が大好きなのに、なぜこんなに音痴なんだろう。歌うたびに落ち込んでしまう。.wav sad_regular_31.wav
move えーん、浪人生になってしまった。自分の未熟さを痛感して、何もかもが暗くなった。.wav sad_regular_32.wav
move えーん、この病気が治る見込みがないと聞いて、絶望的な気持ちでいっぱいです。.wav sad_regular_33.wav
move えーん、何度も失敗して挫折感に苛まれてる。もう一度やり直す自信がない。.wav sad_regular_34.wav
move えーん、留学が終わって日本に帰るのが名残惜しい。こんなに素敵な出会いや思い出があったのに、もう離れなくてはならないなんて寂しすぎる。.wav sad_regular_35.wav
move あの人に傷つけられた時の気持ちは、今でも忘れられない。ぐすん、もう二度とあのような辛い思いをしたくない.wav sad_regular_36.wav
move ぐすん、最近夫婦喧嘩が増えて、とうとう別居することになった。寂しくて泣きたくなる。.wav sad_regular_37.wav
move ぐすん、親友がイジメに遭っていると聞いて、何もできない自分が悲しい。.wav sad_regular_38.wav
move ぐすん、私たちのチームは今日大敗した。私は自分が足を引っ張ってしまったことをとても悔しく思う。.wav sad_regular_39.wav
move ぐすん、熱病で学校を休んだため、友達との大事なイベントに参加できなくなってしまった。.wav sad_regular_40.wav
move ぐすん、この貧困状況で家族がみんな餓えているのを見ると、何もできなくて涙が出た。.wav sad_regular_41.wav
move ぐすん、今回の試験の点数は絶望的に低くて、もう何もできないと思ってしまう。.wav sad_regular_42.wav
move はぁー、今日も寝坊してしまって、会社に遅刻しちゃった。.wav sad_regular_43.wav
move はぁー、私の作品はいつもインパクトがないと言われてる、なんでだろう。.wav sad_regular_44.wav
move はぁー、うちの父親が経営する会社が倒産してしまった。.wav sad_regular_45.wav
move 転んで膝に傷をつけてしまった、はぁー、海にも行けないし、運動もできない.wav sad_regular_46.wav
move はぁー、彼女に裏切られたと知って、心がとても痛い。信じていたのに、どうしてこんなことが起こったんだろう。.wav sad_regular_47.wav
move はぁー、あの人が亡くなったという悲報を聞いて、心が痛くなった。.wav sad_regular_48.wav
move はぁー、今日のプロジェクトでヘマをしてしまい、大切なデータを消してしまった。修復する方法がないと思うと、悲しくてたまらない。.wav sad_regular_49.wav
move あーあ、最近運動不足と食生活の乱れで、医者から高脂血症と診断された。自分がこんなに健康を害しているのを思うと、悲しくなってしまう。.wav sad_regular_50.wav
move あーあ、最近精神疾患で苦しんでいて、友達と会っても楽しめなくて。.wav sad_regular_51.wav
move あぁ、伝染病が猛威を振るっているこの時期、外出もままならず、友達とも会えなくて、本当に寂しい。.wav sad_regular_52.wav
move あぁ、今回の試合で負けたので落胆している。もっと練習しないといけないと感じています。.wav sad_regular_53.wav
move うう、手術後に合併症が起きてしまって、また入院しなければならなくなった。こんなに長い間、病院で過ごすのは辛い。.wav sad_regular_54.wav
move うう、大水害で家が水浸しになってしまった。思い出の品々が水に濡れてしまった。.wav sad_regular_55.wav
move うわあ、今年は渇水で稲作ができなくて、これからどうしよう。.wav sad_regular_56.wav
move うわあ、大水害で家が全壊してしまった。大切な思い出の品や家族の写真も全て失ってしまった。.wav sad_regular_57.wav
move えーん、また足の炎症が起きてしまって、今週末の旅行も行けなくなった。.wav sad_regular_58.wav
move えーん、今回のプレゼンテーションは全然上手くいかなかった。自信がないから、本当に恥ずかしい。.wav sad_regular_59.wav
move ぐすん、あの時あんなこと言わなければよかった。今さら後悔しても仕方ないけど、悔しさで胸がいっぱいだ。.wav sad_regular_60.wav
move ぐすん、先日私が友人の大切なものを壊してしまい、平謝りしても許してもらえなかった。.wav sad_regular_61.wav
move はぁー、この薄暗い部屋で一人でいると、何か寂しい気持ちがしてきて、涙が止まらなくなる。.wav sad_regular_62.wav
move はぁー、彼と別れたけど、未練がまだあって、ずっと彼のことを考えてしまって、もう一度やり直したいと思うけど、もう無理だろうな。.wav sad_regular_63.wav
move ああ、彼は本当に速い！ダッシュの速さは尋常じゃない！.wav surprise_regular_01.wav
move ああ、彼女がこんなに早く編み物ができるなんてビックリしました！.wav surprise_regular_02.wav
move ああ！この歯ブラシは超音波で歯垢を落とすんですか？革命的な技術ですね！.wav surprise_regular_03.wav
move あっ、彼のプレゼンテーションが評価されて、昇進したんですか？すごい！.wav surprise_regular_04.wav
move あっ、この地域はまだ開拓されていないんですか？それは驚きです。.wav surprise_regular_05.wav
move あっ、この株式の価格が急騰している！まさかこんなに早く儲けが出るなんて。.wav surprise_regular_06.wav
move あれ、あのクイズ番組で優勝したのは彼だったの？ビックリ！.wav surprise_regular_07.wav
move あれ、彼女が副収入で月に20万円も稼いでいるって本当ですか？すごい！.wav surprise_regular_08.wav
move あれ、あの人エキストラ出演してたんですか？全然気が付きませんでした。.wav surprise_regular_09.wav
move うぉー、彼女の洞察力には驚きました！こんなに短い時間で私の気持ちに気づくなんて、本当にすごいです。.wav surprise_regular_10.wav
move うぉー、彼女の歌唱力には本当に驚かされました！こんな素晴らしい歌声を披露してくれるなんて想像もしていなかった。.wav surprise_regular_11.wav
move うぉー！あの人の社交性の高さは驚くべきものだ。どこに行っても人気者だ。.wav surprise_regular_12.wav
move うそ！このワインの試飲は無料なの？こんなに美味しいワインが無料で試飲できるなんて信じられない！.wav surprise_regular_13.wav
move うそ！あの人がフィットネスインストラクターだなんて信じられない！.wav surprise_regular_14.wav
move うそ、もうチケットが売り切れてしまったの？あのアーティストのコンサートは本当に人気があるんだね。.wav surprise_regular_15.wav
move うわあ、あの著名人が私たちの祖父の葬儀に参列してくれるとは思ってもみなかった！.wav surprise_regular_16.wav
move うわあ、あの新しいスマホはまだ入手できないんですか？！.wav surprise_regular_17.wav
move うわあ、あのきっかけで結婚するとは思わなかった！.wav surprise_regular_18.wav
move えっ、あの車のスピードは時速200キロ以上だったって？信じられない！.wav surprise_regular_19.wav
move えっ、このアプリの更新速度が早い！たった数日で新しい機能が追加されるとは。.wav surprise_regular_20.wav
move えっ、その小説の主人公は犬だと？こんな斬新なアイデアがあるなんて。.wav surprise_regular_21.wav
move ええ、この本が本当に６００円で買えるんですか？安すぎますね！.wav surprise_regular_22.wav
move ええ、あの二人は毎日キャッチボールをしているんですって！.wav surprise_regular_23.wav
move ええ、彼は本当にジャマイカに行くんですか？私も行ってみたいです。.wav surprise_regular_24.wav
move おお、こんな前代未聞の現象が起こるなんて信じられません！.wav surprise_regular_25.wav
move おお！あの有名人もこのイベントに参加するんですか？.wav surprise_regular_26.wav
move おお、この店はリニューアルされたんですか？内装が全然違いますね！.wav surprise_regular_27.wav
move おっと、あの方が乗っているのは人力車ですか？こんなに現代的な街で見かけるなんて意外ですね。.wav surprise_regular_28.wav
move おっと、この会場のキャパシティーは500人だったのに、もう600人以上も入ってるよ！.wav surprise_regular_29.wav
move おっと、その新情報はまだ公表されていなかったはずですが、どうやって入手したのですか？.wav surprise_regular_30.wav
move おや、この装備はかなり高性能だね。こんなに進歩しているとは知りませんでした。.wav surprise_regular_31.wav
move おや、あの子バッティングが上手いんですか？知らなかった。.wav surprise_regular_32.wav
move おや、あなたも孔子について勉強しているんですか？.wav surprise_regular_33.wav
move なに、あの人が無人島に1年間住んでいたって？本当に生きて帰ってきたんですか？.wav surprise_regular_34.wav
move なに？彼女はアルゼンチンに住んでいたことがあるんですか？すごく興味深いですね。.wav surprise_regular_35.wav
move なに？あの有名人が結婚したってうわさを聞いたけど、本当なのかしら？.wav surprise_regular_36.wav
move へぇ、あの人が映画のオーディションを受けることになったんだって！.wav surprise_regular_37.wav
move へぇ、あなたのタイピングスピードは時速100語以上なんですか？すごい！.wav surprise_regular_38.wav
move へぇ、このアプリはボタン一つで自動的に美しいグラフを生成できるんですか？すごい技術ですね！.wav surprise_regular_39.wav
move ほう、あの会社のシェアがこんなに伸びたとは驚きですね。.wav surprise_regular_40.wav
move ほう、彼女はバッティングが得意だって？意外な才能があるんですね！.wav surprise_regular_41.wav
move ほう、ディベート大会で優勝したんですか？.wav surprise_regular_42.wav
move まあ、あの森の奥に妖精が住んでいるっていう伝説は知っていましたが、本当に妖精がいるとは思わなかったです。.wav surprise_regular_43.wav
move まあ、彼が女装をするとは想像もしませんでした。.wav surprise_regular_44.wav
move まあ、彼が次の市長選挙に出馬するとは驚きですね。.wav surprise_regular_45.wav
move わあ、あの人はあんなに信仰心が厚かったんですか？驚きました。.wav surprise_regular_46.wav
move わあ、彼のチェンジアップの球速がこんなに速くなるなんて驚きです！.wav surprise_regular_47.wav
move わあ、あの選手のシュートはすごい角度から入った！.wav surprise_regular_48.wav
move わお、あの高校生があんなに優秀なんですか？すごいですね！.wav surprise_regular_49.wav
move わお、あの若い人がベンチャー企業を立ち上げたんだって！すごいですね！.wav surprise_regular_50.wav
move わお！あのゲームの攻略法を知っているんですか？すごい！.wav surprise_regular_51.wav
move ん？彼があんなに上手いのにアマチュアなの？驚きました。.wav surprise_regular_52.wav
move ん？あの映画に出演している女優さんは、去年まで普通の会社員だったって本当ですか？.wav surprise_regular_53.wav
move ん？今度のゲームのボスキャラがこんなに強いとは思わなかった！.wav surprise_regular_54.wav
move やあ！あの蜘蛛、大きすぎてびっくりしました。.wav surprise_regular_55.wav
move やあ！突然の来客が知らない男性で驚きました。.wav surprise_regular_56.wav
move やあ！急に雷が鳴り響いて、めっちゃ驚かされた。.wav surprise_regular_57.wav
move ああ、そうか。あの人がプロのゲーマーじゃなくて、ただのお遊びだったなんて。.wav surprise_regular_58.wav
move ああ、彼女は有名な写真家なんですか？知らなかった！.wav surprise_regular_59.wav
move あっ、あの新しい映画の音楽は有名な作曲家が作ったんですか？素晴らしい！.wav surprise_regular_60.wav
move あっ、こんなに美味しいラーメンは初めてです。.wav surprise_regular_61.wav
move あれ、彼女が免許を持っていないって本当ですか？今時、免許を持っていない人って珍しいですよね。.wav surprise_regular_62.wav
move あれ、彼女の義父は有名な俳優さんだったの？.wav surprise_regular_63.wav
move うぉー！アウトドア派の人にはたまらないキャンプ場を見つけたんです！.wav surprise_regular_64.wav
move うぉー、あなたもテレパシーの力を信じていますか？.wav surprise_regular_65.wav
move うそ、副収入で年収1000万円も稼いでいるなんて信じられません！.wav surprise_regular_66.wav
move うそ、ついにその事件の真相を解明したんですか？すごい！.wav surprise_regular_67.wav
move うわあ、彼女が全米チャンピオンになったんですか？すごい！.wav surprise_regular_68.wav
move うわあ、タコが足を伸ばしている！こんなに伸びるのは初めて見ました。.wav surprise_regular_69.wav
move えっ、そのアニメの主人公の声優さんはこの人なんですか？！知らなかった！.wav surprise_regular_70.wav
move えっ、その商品が即決で落札されました！早いですね。.wav surprise_regular_71.wav
move ええ、この小説の世界は異空間のような場所に設定されているんですか？想像力がすごいですね。.wav surprise_regular_72.wav
move ええ、あの人は無人島で１年生活したことがあるんですか？すごく興味深い話ですね。.wav surprise_regular_73.wav
move おお、あの有名なテニスコーチが来てる！.wav surprise_regular_74.wav
move おお、安いホテルなのに個室があるんですか？.wav surprise_regular_75.wav
move おっと、あの映画のシーンを再現したんですか？すごくリアルに見えますね！.wav surprise_regular_76.wav
move おっと、この料理は無添加なのに、こんなに美味しいんですか？.wav surprise_regular_77.wav
move おや？あの家の紋章って、ローマ字の「M」なんですか？意外なデザインですね。.wav surprise_regular_78.wav
move おや、紅葉狩りに行くために早朝から起きてるんですか？すごく熱心ですね！.wav surprise_regular_79.wav
move なに？童心に帰って、公園でブランコなんてしてるんですか？.wav surprise_regular_80.wav
move なに？あの本が再刊されるなんて聞いてなかった！.wav surprise_regular_81.wav
move へぇ、彼女の給与って私の方が高いの？それはちょっと意外だな。.wav surprise_regular_82.wav
move へぇ？もう降雪が始まったんですか？もう冬が来たんだなと実感しますね。.wav surprise_regular_83.wav
move ほう、エベレストの登頂に成功したんですか？凄いですね！.wav surprise_regular_84.wav
move ほう、初心者でもあんなに上手に弾けるんですか？すごい才能ですね！.wav surprise_regular_85.wav
move まあ！あの大物俳優が私たちの提案に諾意してくれるなんて、信じられない！.wav surprise_regular_86.wav
move まあ、あの人が作ったガレージキット、本当にプロレベルの出来栄えだ！.wav surprise_regular_87.wav
move わあ、ついに北と南が統一されたんですか？世界はどんどん変わっていくんですね。.wav surprise_regular_88.wav
move わあ！あの有名な画家が自分の絵筆を手作りするとは驚きですね。.wav surprise_regular_89.wav
move わお、こんなにたくさんのマイルを換金できるなんて、クレジットカードってすごいですね！.wav surprise_regular_90.wav
move わお、スポーツで体重が10キロ減ったんですか？.wav surprise_regular_91.wav
move ん？日本でもラクロスが人気になってきたんですね！.wav surprise_regular_92.wav
move ん？あのアラーム音、私もよく使っているんです！.wav surprise_regular_93.wav
move やあ、そのペット、本当に小さくて可愛いですね！.wav surprise_regular_94.wav
move やあ、あの人が君の結婚相手？本当に意外だ。.wav surprise_regular_95.wav
